# Generated by Django 3.2.10 on 2021-12-21 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials_walls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Стены')),
            ],
        ),
        migrations.CreateModel(
            name='Mkr_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Микрорайон')),
            ],
        ),
        migrations.CreateModel(
            name='Pas_chjs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pas_number', models.IntegerField()),
                ('pas_adress', models.CharField(max_length=350)),
                ('stages', models.IntegerField(blank=True)),
                ('electric', models.BooleanField(default=True)),
                ('apis', models.IntegerField(blank=True)),
                ('living', models.IntegerField(blank=True)),
                ('childrens', models.IntegerField(blank=True)),
                ('characteristic', models.TextField(blank=True)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('date_owner', models.DateField()),
                ('woker_mchs', models.CharField(max_length=200)),
                ('woker_date', models.DateField()),
                ('unfineshed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_update', models.DateTimeField(auto_now=True)),
                ('mkr_name_pas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pas_chjs.mkr_name', verbose_name='Микрорайон')),
                ('walls_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pas_chjs.materials_walls', verbose_name='Стены')),
            ],
        ),
    ]
